﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace SmartAgriculture
{
    public partial class Cropforecast
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Moisture", @"Moisture"),new InputOutputColumnPair(@"Temperature", @"Temperature"),new InputOutputColumnPair(@"PH", @"PH"),new InputOutputColumnPair(@"Nitrogen", @"Nitrogen"),new InputOutputColumnPair(@"Phosphorus", @"Phosphorus"),new InputOutputColumnPair(@"Potassium", @"Potassium")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"CropType",outputColumnName:@"CropType"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Moisture",@"Temperature",@"PH",@"Nitrogen",@"Phosphorus",@"Potassium",@"CropType"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.LbfgsPoissonRegression(new LbfgsPoissonRegressionTrainer.Options(){L1Regularization=0.03125F,L2Regularization=1.443795F,LabelColumnName=@"MatchingRate",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
