// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SmartAgriculture
{
    public partial class Nitrogenforecast
    {
        /// <summary>
        /// model input class for Nitrogenforecast.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Date")]
            public DateTime Date { get; set; }

            [ColumnName(@"CropType")]
            public string CropType { get; set; }

            [ColumnName(@"Temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"Moisture")]
            public float Moisture { get; set; }

            [ColumnName(@"Nitrogen")]
            public float Nitrogen { get; set; }

            [ColumnName(@"pH")]
            public float PH { get; set; }

            [ColumnName(@"NitrogenFertilizer")]
            public float NitrogenFertilizer { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Nitrogenforecast.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Date")]
            public float Date { get; set; }

            [ColumnName(@"CropType")]
            public float[] CropType { get; set; }

            [ColumnName(@"Temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"Moisture")]
            public float Moisture { get; set; }

            [ColumnName(@"Nitrogen")]
            public float Nitrogen { get; set; }

            [ColumnName(@"pH")]
            public float PH { get; set; }

            [ColumnName(@"NitrogenFertilizer")]
            public float NitrogenFertilizer { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Nitrogenforecast.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
